# Generated by Django 2.1.5 on 2019-02-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='username',
        ),
    ]
