# Generated by Django 2.1.5 on 2019-02-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_humitureinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='humitureinfo',
            name='hum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='humitureinfo',
            name='tem',
            field=models.IntegerField(null=True),
        ),
    ]
