# Generated by Django 2.1.5 on 2019-02-25 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190225_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HumitureInfo',
        ),
    ]
