# Generated by Django 2.1.5 on 2019-02-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_delete_humitureinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumitureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('temp', models.IntegerField(null=True)),
                ('humi', models.IntegerField(null=True)),
            ],
        ),
    ]
