# Generated by Django 2.1.5 on 2019-02-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190225_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='wifi_elec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.CharField(max_length=20)),
                ('elec', models.CharField(max_length=20)),
            ],
        ),
    ]
