# Generated by Django 2.1.5 on 2019-02-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_info_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('now_version', models.CharField(max_length=20)),
                ('new_version', models.CharField(max_length=20)),
                ('need_update', models.IntegerField()),
            ],
        ),
    ]
