# Generated by Django 2.1.5 on 2019-02-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=20)),
                ('now_version', models.CharField(max_length=20)),
            ],
        ),
    ]
