# Generated by Django 2.1.5 on 2019-02-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190228_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='alias',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
