# Generated by Django 2.1.5 on 2019-02-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_version_alias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='version',
        ),
    ]
