# Generated by Django 2.1.5 on 2019-02-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_delete_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('sn', models.IntegerField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=20)),
                ('now_version', models.CharField(max_length=20)),
                ('new_version', models.CharField(max_length=20)),
                ('need_update', models.IntegerField()),
            ],
        ),
    ]
