# Generated by Django 2.1.5 on 2019-02-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_humitureinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humitureinfo',
            name='date',
            field=models.DateTimeField(auto_now=True, max_length=20),
        ),
    ]
