# Generated by Django 2.1.5 on 2019-02-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20190228_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='serial_number',
        ),
    ]
